# Generated by Django 3.2.8 on 2021-10-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211030_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='IngridientAmount',
            new_name='IngredientAmount',
        ),
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
