# Generated by Django 3.2.8 on 2021-11-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211031_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hexcolor',
            new_name='color',
        ),
    ]
