# Generated by Django 3.2.8 on 2021-11-09 23:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211109_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.CheckConstraint(check=models.Q(('ingredient', django.db.models.expressions.F('recipe')), _negated=True), name='unique_ingredient_in_recipe'),
        ),
    ]
