# Generated by Django 3.2.8 on 2021-11-08 22:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_user_is_not_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_is_not_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('author')), _negated=True), name='subscriber_is_not_author'),
        ),
    ]
