# Generated by Django 3.2.8 on 2021-11-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211108_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
